version: '2'

services:
  mplayer-user-db:
    container_name: "mplayer-user-db"
    image: 'bitnami/postgresql:16'
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${USER_DB_USERNAME}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DB: ${USER_DB_DATABASE}
    networks:
      - mplayer-net
  mplayer-broker:
    container_name: "mplayer-broker"
    image: 'rabbitmq:3-management'
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - mplayer-net

networks:
  mplayer-net:
volumes:
  cache:
    driver: local