server:
  port: 8080

spring:
  application:
    name: mplayer
  flyway:
    schemas: public
  datasource:
    url: jdbc:postgresql://${USER_DB_HOST}:5432/${USER_DB_DATABASE}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
