server:
  port: 8080

spring:
  application:
    name: mplayer
  flyway:
    enabled: ${APPLICATION_FLYWAY_ENABLED}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  datasource:
    url: ${MPLAYER_DB_URI}
    username: ${MPLAYER_DB_USERNAME}
    password: ${MPLAYER_DB_PASSWORD}
    driver-class-name: ${MPLAYER_DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: ${MPLAYER_DB_DIALECT}
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_APP_PASS}
    protocol: 'smtp'
    host: 'smtp.gmail.com'
    port: 587
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    port: ${RABBITMQ_PORT}
  modulith:
    events:
      externalization:
        enabled: true
      republish-outstanding-events-on-restart: true
      events:
        jdbc:
          schema-initialization:
            enabled: true

auth:
  jwt:
    private-rsa: ${PRIVATE_RSA}
    public-rsa: ${PUBLIC_RSA}
  aws:
    access-key: ${ACCESS_KEY_AWS}
    secret-key: ${SECRET_KEY_AWS}
  last-fm:
    api-key: ${LAST_FM_API_KEY}

services:
  endpoint:
    user: http://localhost:${server.port}/api/v1/user
