server:
  port: 8080

spring:
  application:
    name: mplayer
  datasource:
    url: jdbc:postgresql://${MPLAYER_DB_HOST}:5432/${MPLAYER_DB_DATABASE}
    username: ${MPLAYER_DB_USERNAME}
    password: ${MPLAYER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_APP_PASS}
    protocol: 'smtp'
    host: 'smtp.gmail.com'
    port: 587
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    port: 5672
  modulith:
    events:
      externalization:
        enabled: true
      republish-outstanding-events-on-restart: true
      events:
        jdbc:
          schema-initialization:
            enabled: true

auth:
  jwt:
    private-rsa: ${PRIVATE_RSA}
    public-rsa: ${PUBLIC_RSA}