name: Docker image deploy

on:
  workflow_dispatch:

env:
  APP_API_NAME: mplayer-api
  TAG_VERSION: v1.0.0 # must change it on every new tag release

jobs:
  push_image_docker_registry:
    name: Push Docker image to Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login on registry
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build and push docker image
        id: push
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_API_NAME }}:${{ env.TAG_VERSION }}